name: CI
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        goenv_native_ext: ["", "1"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Bash Version
        run: bash --version
      - name: Run Unit Tests
        run: |
          bash
          make test
        env:
          GOENV_NATIVE_EXT: ${{ matrix.goenv_native_ext }}
